cmake_minimum_required(VERSION 3.16 FATAL_ERROR)

set(PROJECT_NAME GGXrdKeyboardMod)
set(CMAKE_BUILD_TYPE Debug)
set(CMAKE_CXX_STANDARD 17)

project(${PROJECT_NAME} C CXX)

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/$<CONFIGURATION>")
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/$<CONFIGURATION>")

set(INJECTOR_DIR injector)
file(GLOB_RECURSE INJECTOR_SOURCES ${INJECTOR_DIR}/*.cpp)

set(MOD_LIB_NAME ${PROJECT_NAME})
set(MOD_DIR mod)
file(GLOB_RECURSE MOD_SOURCES ${MOD_DIR}/*.cpp)

add_executable(${PROJECT_NAME}Injector ${INJECTOR_SOURCES})

add_library(${MOD_LIB_NAME} SHARED ${MOD_SOURCES})
include_directories(${MOD_LIB_NAME} PRIVATE ${MOD_DIR})
